#!/usr/bin/env bash

# Sets up a service key for the given instance, saves it
# to a local file and then displays it in the terminal.

set -o errexit
source shared

# Create service key for the new instance
cf create-service-key "$instance" "$key"

# Copy service key contents into local file
cf service-key "$instance" "$key" | sed "1,2d" > "$keyfile"

# Display contents of service key
jq < "$keyfile"
